### ISSUE TITLE
How about just history of cursor positions across files?

### ISSUE THREAD

**Issue by dmilith** [FichteFoll/FileHistory#39]
... and just add ability to go "backward" + "forward" ? I'm trying to get that feature since beginning of life, but nothing does it well :(

**Comment by FichteFoll** [comment]
That's an interesting idea, but it goes beyond the scope of this package and will not be covered by it.

I'd rather implement this in a separate package but most likely won't since I personally don't have a need for a feature like this and wouldn't know how it would or should be used (not to mention lack of time).
