### ISSUE TITLE
Ability to remove dead files from the Session.sublime_session file

### ISSUE THREAD

**Issue by stephen147** [FichteFoll/FileHistory#52]
If I use the cleanup_file_history command it doesn't remove the dead files found in:

`...\Sublime Text\Data\Local\Session.sublime_session`

Would it be possible to remove the dead files from this file or would there be problems seeing as sublime text may need to be closed?

**Comment by FichteFoll** [comment]
Yes, indeed this isn't a good idea to solve from within a plugin and also part of the reason for FileHistory to maintain its own history.

If you really need to clean up old dead files from the session, I suggest the following tool instead: 

https://github.com/STealthy-and-haSTy/SublimeScraps/tree/master/session_cleaner

**Comment by stephen147** [comment]
Thanks, I did see that but it removes dead projects and not the files from the session file.

**Comment by FichteFoll** [comment]
The wording kind of implied it would clean up files as well, but I admit I hadn't re-reviewed the source code to verify. I suggest creating an issue there and asking for support of that because it seems like something that would fall within the scope of that script. It should of course be disableable (or not even the default) because of temporarily unavailable mounts.

**Comment by stephen147** [comment]
Ok, I'll add an issue over there. Thanks.
